mysql:
  host: localhost
  port: 3306
  database: minecraft
  username: root
  password: ""

auction:
  duration-hours: 24
  item-lore:
    - ""
    - "&fSeller: &#facc15%seller%"
    - "&fPrice: &#00fc88$%price%"
    - "&fTime: &7%time%"
    - ""
    - "&eClick to buy"

sounds:
  click: UI_BUTTON_CLICK
  success: ENTITY_PLAYER_LEVELUP
  error: ENTITY_VILLAGER_NO
  open-menu: BLOCK_CHEST_OPEN
