mysql:
  host: localhost
  port: 3306
  database: minecraft
  username: root
  password: ""
auction:
  duration-hours: 24
  minimum-price: 100
  item-lore:
    - ""
    - "&fNgười bán: &#facc15%seller%"
    - "&fGiá: &#00fc88$%price%"
    - "&fThời hạn: &7%time%"
    - ""
    - "&eNhấp để mua vật phẩm này"
sounds:
  click: UI_BUTTON_CLICK
  success: ENTITY_PLAYER_LEVELUP
  error: ENTITY_VILLAGER_NO
  open-menu: BLOCK_CHEST_OPEN
